function plot_stress_image(pred,u_test,i,ii,iii,iv,v,pixel)
set(gca,'fontname','serif','fontsize',12) 
% set(gca,'TickLabelInterpreter','latex')
set(0,'defaulttextInterpreter','latex') %latex axis labels
set(gca,'TickLabelInterpreter','latex')

subplot(5,3,1)
contourf(reshape(u_test(i,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,2)
contourf(reshape(pred(i,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,3)
contourf(reshape((abs(pred(i,:,:)-u_test(i,:,:))),pixel,pixel),10,'LineStyle','none'); caxis([0 100]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
%% ------
subplot(5,3,4)
contourf(reshape(u_test(ii,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,5)
contourf(reshape(pred(ii,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,6)
contourf(reshape((abs(pred(ii,:,:)-u_test(ii,:,:))),pixel,pixel),10,'LineStyle','none'); caxis([0 100]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
%% ------
subplot(5,3,7)
contourf(reshape(u_test(iii,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,8)
contourf(reshape(pred(iii,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,9)
contourf(reshape((abs(pred(iii,:,:)-u_test(iii,:,:))),pixel,pixel),10,'LineStyle','none'); caxis([0 100]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
%% ------
subplot(5,3,10)
contourf(reshape(u_test(iv,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,11)
contourf(reshape(pred(iv,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,12)
contourf(reshape((abs(pred(iv,:,:)-u_test(iv,:,:))),pixel,pixel),10,'LineStyle','none'); caxis([0 100]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
%% ------
subplot(5,3,13)
contourf(reshape(u_test(v,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,14)
contourf(reshape(pred(v,:,:),pixel,pixel),50,'LineStyle','none'); caxis([0 350]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
subplot(5,3,15)
contourf(reshape((abs(pred(v,:,:)-u_test(v,:,:))),pixel,pixel),10,'LineStyle','none'); caxis([0 100]);colorbar;colormap(jet)%;set(gca,'TickLabelInterpreter','latex')
set(gca,'fontname','serif','fontsize',12) 
